export component BatteryIndicator inherits Rectangle {
    in property<float> voltage;

    width: 90px;
    height: 45px;
    border-width: 2px;
    border-color: white;
    background: transparent;

    Rectangle {
        x: 1px;
        y: 5px;
        width: parent.width - 10px;
        height: parent.height - 10px;
        border-width: 2px;
        border-color: white;
        background: transparent;
    }

    Rectangle {
        x: parent.width - 8px;
        y: (parent.height * 0.5) - 6px;
        width: 6px;
        height: 12px;
        background: white;
    }

    Rectangle {
        x: 3px;
        y: 7px;
        width: (voltage / 13.0) * (parent.width - 16px);
        height: parent.height - 14px;
        background: rgb((1.0 - voltage / 13.0) * 255, (voltage / 13.0) * 255, 0);
    }
}
