import { VerticalBox, Button } from "std-widgets.slint";

export component MainWindow inherits Window {
    width: 300px;
    height: 150px;

    VerticalBox {
        alignment: center;
        spacing: 10px;

        Text {
            text: "Hello World";
            color: green;
            horizontal-alignment: center;
        }

        Button {
            text: "Click Me";
            clicked => {
                root.clicked();
            }
        }
    }

    callback clicked;
}
